### ISSUE TITLE
[TASK] Refactoring VolatileInstaller to Service + CommandController

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/site#12]
Depends on https://github.com/FluidTYPO3/fluidcontent_core/pull/186

**Comment by NamelessCoder** [comment]
Hmm, didn't see the "depends on" before merging this because it wasn't in the PR. It's a minor detail and I expect Xaver to have a look at the FCC issue quite soon, but next time if there are dependencies, please write that directly in the pull request so we (read: I) don't miss it ;)
