### ISSUE TITLE
The package "site" depends on "typo3/cms" which is not present in the system.

### ISSUE THREAD

**Issue by 23b** [FluidTYPO3/site#14]
I have the same Issue on two Typo3 6.2.14 Installations when trying to install EXT:site 1.4.2. I get this error. "The package "site" depends on "typo3/cms" which is not present in the system."
I already tried removing the dependency from the typo3conf/ext/site/composer.json without success. One might think "Were does it get this dependency from otherwise?"
The only thing that fixed this Issue for me is to manually edit PackageStates.php and set the package to active.

Then after trying to create a Plugin i was faced with yet another error:

"The action "welcome" (controller "Distribution") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php."
So I hacked this into the ext_localconf.php of EXT:site:

Tx_Extbase_Utility_Extension::configurePlugin(
	$_EXTKEY,
	'site',
	array(
		'Distribution' => 'welcome',
	),
);

Which works but then I am faced again with the same, first error:
The package "site" depends on "typo3/cms" which is not present in the system.

I would be great if you could find out what is going wrong here. This Kickstarter has been a real Handbreak to my attempt to learn how to implement Fluid powered Typo3. Especially since I don't find any other way to get started with this.

**Comment by thomaszbz** [comment]
I ran into the same issue:

 I ran into the same issue when trying to install "FluidTYPO3 Kickstarter" after a fresh install of 6.2.14. Message: 

> The package "site" depends on "typo3/cms" which is not present in the system."

Log says

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1382276561: The package "site" depends on "typo3/cms" which is not present in the system. | UnexpectedValueException thrown in file /var/webadmin/typo3_src/typo3/sysext/core/Classes/Package/DependencyResolver.php in line 140. Requested URL: http://172.17.1.83/typo3/mod.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=0824411d55e00aab71850f548f22c1e2587a0fa0&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bextension%5D=34852&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=installDistribution&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=Download ". Before, I ran up-to-date composer with composer.json/composer.lock installed in /var/www/typo3 which is TYPO3's base directory for my installation (with composer install)

Comment of Markus Klein on this on Slack:

> Checked this now with the code. This is simply a wrong composer.json! From what I see there is no check for typo3/cms. The core composer names are always typo3/cms-*.
The fallback I was talking of was only related to master and is a fallback for typo3/cms-cms, which does not exist anymore on master.
So please report the issue to the extension author (Claus I guess in this case). The require should be typo3/cms-core

**Comment by NamelessCoder** [comment]
That's kind of stupid since the official name of the TYPO3 packagist package is `typo3/cms`. Which basically means that TYPO3 doesn't know that TYPO3 is installed. It has to be told that a specific TYPO3 extension is installed.

I'd change this as soon as possible in the EM itself. It literally makes no sense that `typo3/cms` is not recognised by the EM. None at all.

https://github.com/FluidTYPO3/site/commit/29db0334546eac55531576c032aa789ac7f919fa

(If you think you are reading a bit of frustration into this then you are not wrong. As you will soon learn, every FluidTYPO3 package uses this **correct** `typo3/cms` dependency and fixing it here will just mean you encounter the next one. What that means in the end is several hours of work yet again; all to match an esoteric behavior of the EM. It's getting a little tedious to me at this point). Sorry to digress like that, I just want to explain how frustrating it is. Thanks guys nonetheless for providing a solution!

**Comment by thomaszbz** [comment]
Sorry, I felt this was a normal bug, not an emotional issue.

My point on this is that it's a big showstopper for new users performing their very first action after a fresh install.

**Comment by NamelessCoder** [comment]
> My point on this is that it's a big showstopper for new users performing their very first action after a fresh install.

That's exactly why it is so frustrating ;)

**Comment by NamelessCoder** [comment]
https://forge.typo3.org/issues/65867

**Comment by thomaszbz** [comment]
I'd rather prefer a feature removal than leaving this bug unsolved.

**Comment by NamelessCoder** [comment]
In case you missed it, it's already fixed: https://github.com/FluidTYPO3/site/commit/29db0334546eac55531576c032aa789ac7f919fa - and deployed to TER - http://typo3.org/extensions/repository/view/site.

**Comment by thomaszbz** [comment]
Ah, indeed missed it. Thanks for the fix!

**Comment by thomaszbz** [comment]
Just gave it a try:

> Congratulations...
> You successfully installed the distribution: site
