### ISSUE TITLE
[ 6.2 LTS / 7.5 ] Start configuration by clicking extension name not working

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/site#21]
On the new Typo3 this is no more possible. Maybe you have to provide the "engine button" action to do this?

---

Also on 6.2 LTS the same thing, the extension cannot be clicked.

**Comment by jmverges** [comment]
Hi @julianxhokaxhiu,

are you using development version or TER? Development version moves kickstarting process to a service + command, so you can configure it now with terminal. The plan is to create some Backend Module like the one provided by Builder. https://github.com/FluidTYPO3/site/pull/18

**Comment by julianxhokaxhiu** [comment]
Both and both are not working. Is it documented somewhere? I didn't knew about that, otherwise I would have done it :) Sorry

**Comment by julianxhokaxhiu** [comment]
Found the way to launch it via CLI and now I got this error @jmverges can you please fix this?

```zsh
PHP Fatal error:  Undefined class constant 'DEFAULT_TYPOSCRIPT_TEMPLATE_TITLE' in /var/www/project/htdocs/typo3conf/ext/site/Classes/Service/KickStarterService.php on line 222
```

command line used

```zsh
./typo3/cli_dispatch.phpsh extbase site:kickstarter default 1 1 myextname
```

**Comment by NamelessCoder** [comment]
Clicking extension title is replaced by a proper backend module in next version. The commandline will continue to function as it did before.
