### ISSUE TITLE
7.6.4 No Configuration

### ISSUE THREAD

**Issue by Thomas2love** [FluidTYPO3/site#26]
After install of the distribution you get no configuration button, as seen in the video. In the extension manager there is no option to click the title, also there is no cogwheel to click. I then hacked a uri to get to it, but it gave me an empty screen with only a 'Configuration' header.

**Comment by NamelessCoder** [comment]
Hi Thomas,

The configuration hook has been replaced by a true backend module. After installing the extension you may need to reload the entire backend before you see it!
