### ISSUE TITLE
VHS outdated for CMS 7

### ISSUE THREAD

**Issue by gaumondp** [FluidTYPO3/site#6]
Trying to install brand new distribution "FluidTYPO3 site kickstarter" from CMS7 and got this error: 
- Could not install distribution 'site'
- vhs was requested to be downloaded in different versions.

I tried then to install VHS 2.2.0 prior to installing the distribution and got this message :
- Could not install distribution 'vhs' Your TYPO3 version is higher than this extension requires.
- It requires TYPO3 versions 6.0.0 - 6.2.99"

**Comment by mrvoss** [comment]
I also got the "vhs was requested to be downloaded in different versions" on a fresh 6.2 install. The TYPO3 dependency solver doesn't seem to be the smartest ...

I solved this by installing fluidcontent_core (1.0.2) first, which installs its dependencies flux and vhs (in version 2.1.4). After that, ext:site does install.

**Comment by albig** [comment]
Same here. Install in fresh 6.2.10-dev is not possible due to wrong VHS dependency.

**Comment by mhmli** [comment]
Same here in 6.2.10 on a clean (VHS-free) install.

**Comment by ste101** [comment]
I made a bug report:
https://forge.typo3.org/issues/66152
