### ISSUE TITLE
Extension cannot load dependency VHS

### ISSUE THREAD

**Issue by mhmli** [FluidTYPO3/site#7]
When trying to load this distribution via TYPO3 6.2.10 Backend, the import fails with the message “Could not install distribution 'site'. vhs was requested to be downloaded in different versions.”.

**Comment by NamelessCoder** [comment]
Check in TER for an update to `fluidcontent_core` in a few moments - once that is live, this dependency problem should go away :)

**Comment by mhmli** [comment]
Great, thanks Claus. :)

**Comment by mhmli** [comment]
Confirmed: distribution now works fine :)
